#!/usr/bin/env bash
# oCabra — First-run installation script
# Usage: bash setup.sh
# Safe to run multiple times (idempotent).
set -euo pipefail

# ---------------------------------------------------------------------------
# Colors & helpers
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }
fatal() { err "$@"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ---------------------------------------------------------------------------
# 1. Check prerequisites
# ---------------------------------------------------------------------------
echo -e "\n${BOLD}=== oCabra Setup ===${NC}\n"

info "Checking prerequisites..."

# Docker
if ! command -v docker &>/dev/null; then
    fatal "Docker is not installed. See https://docs.docker.com/engine/install/"
fi
ok "Docker found: $(docker --version)"

# Docker Compose (plugin or standalone)
if docker compose version &>/dev/null; then
    COMPOSE="docker compose"
    ok "Docker Compose found: $(docker compose version --short)"
elif command -v docker-compose &>/dev/null; then
    COMPOSE="docker-compose"
    ok "Docker Compose found: $(docker-compose --version)"
else
    fatal "Docker Compose is not installed. See https://docs.docker.com/compose/install/"
fi

# NVIDIA driver
if ! command -v nvidia-smi &>/dev/null; then
    fatal "nvidia-smi not found. Install NVIDIA drivers first."
fi
ok "NVIDIA driver: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1)"

# NVIDIA Container Toolkit
if ! docker info 2>/dev/null | grep -qi "nvidia\|Runtimes.*nvidia"; then
    if [ -f /usr/bin/nvidia-container-runtime ] || [ -f /usr/bin/nvidia-container-toolkit ]; then
        warn "NVIDIA Container Toolkit is installed but may not be configured as a Docker runtime."
        warn "Run: sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker"
    else
        fatal "NVIDIA Container Toolkit not found. See https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
    fi
fi
ok "NVIDIA Container Toolkit available"

# Show GPU info
echo ""
info "Detected GPUs:"
nvidia-smi --query-gpu=index,name,memory.total --format=csv,noheader | while IFS= read -r line; do
    echo "      GPU $line"
done
echo ""

# ---------------------------------------------------------------------------
# 2. Create required directories
# ---------------------------------------------------------------------------
info "Creating data directories..."

# Default AI models root (can be overridden in .env)
AI_MODELS_ROOT="${AI_MODELS_ROOT:-/docker/ai-models}"

dirs=(
    "./data/postgres_data"
    "./caddy/caddy_data"
    "./caddy/caddy_config"
    "${AI_MODELS_ROOT}/ocabra/models"
    "${AI_MODELS_ROOT}/ocabra/hf_cache"
    "${AI_MODELS_ROOT}/ollama"
)

for d in "${dirs[@]}"; do
    if [ ! -d "$d" ]; then
        mkdir -p "$d"
        ok "Created $d"
    else
        ok "Exists  $d"
    fi
done

# ---------------------------------------------------------------------------
# 3. Generate .env from .env.example
# ---------------------------------------------------------------------------
if [ -f .env ]; then
    ok ".env already exists (not overwriting)"
else
    if [ ! -f .env.example ]; then
        fatal ".env.example not found in project root"
    fi

    info "Creating .env from .env.example..."
    cp .env.example .env

    # Generate a stable JWT_SECRET
    JWT_SECRET="$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
                 || openssl rand -hex 32 2>/dev/null \
                 || head -c 32 /dev/urandom | xxd -p | tr -d '\n')"

    # Generate a gateway service token
    GATEWAY_TOKEN="$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
                     || openssl rand -hex 32 2>/dev/null \
                     || head -c 32 /dev/urandom | xxd -p | tr -d '\n')"

    # Write secrets into .env (append to the auth section)
    {
        echo ""
        echo "# --- Generated by setup.sh ---"
        echo "JWT_SECRET=${JWT_SECRET}"
        echo "GATEWAY_SERVICE_TOKEN=${GATEWAY_TOKEN}"
    } >> .env

    ok ".env created with generated secrets"

    # Prompt for optional customization
    echo ""
    read -rp "$(echo -e "${CYAN}Admin username${NC} [ocabra]: ")" admin_user
    admin_user="${admin_user:-ocabra}"

    read -rp "$(echo -e "${CYAN}Admin password${NC} [ocabra]: ")" admin_pass
    admin_pass="${admin_pass:-ocabra}"

    read -rp "$(echo -e "${CYAN}PostgreSQL password${NC} [change_me_in_production]: ")" pg_pass
    pg_pass="${pg_pass:-change_me_in_production}"

    # Apply values
    sed -i "s|^OCABRA_ADMIN_USER=.*|OCABRA_ADMIN_USER=${admin_user}|" .env 2>/dev/null || true
    sed -i "s|^OCABRA_ADMIN_PASS=.*|OCABRA_ADMIN_PASS=${admin_pass}|" .env 2>/dev/null || true
    # Commented out in .env.example, so append if not already set
    if ! grep -q "^OCABRA_ADMIN_USER=" .env; then
        echo "OCABRA_ADMIN_USER=${admin_user}" >> .env
    fi
    if ! grep -q "^OCABRA_ADMIN_PASS=" .env; then
        echo "OCABRA_ADMIN_PASS=${admin_pass}" >> .env
    fi

    if [ "$pg_pass" != "change_me_in_production" ]; then
        sed -i "s|change_me_in_production|${pg_pass}|g" .env
    fi

    ok "Configuration applied"
fi

# ---------------------------------------------------------------------------
# 4. Determine which services to build
# ---------------------------------------------------------------------------
# Core services that always run
CORE_SERVICES="api frontend postgres redis caddy"

# Optional GPU services — only include if their build context exists
OPTIONAL_SERVICES=""

if [ -d "./Hunyuan3D-2.1" ]; then
    OPTIONAL_SERVICES="$OPTIONAL_SERVICES hunyuan"
fi
if [ -d "./services/comfyui" ]; then
    OPTIONAL_SERVICES="$OPTIONAL_SERVICES comfyui"
fi
if [ -d "./services/a1111" ]; then
    OPTIONAL_SERVICES="$OPTIONAL_SERVICES a1111"
fi

# Build only available services
BUILD_SERVICES="$CORE_SERVICES $OPTIONAL_SERVICES"

info "Services to build: ${BUILD_SERVICES}"

# ---------------------------------------------------------------------------
# 5. Build
# ---------------------------------------------------------------------------
echo ""
info "Building Docker images (this may take a while on first run)..."
$COMPOSE build $BUILD_SERVICES

ok "Docker images built"

# ---------------------------------------------------------------------------
# 6. Start
# ---------------------------------------------------------------------------
echo ""
info "Starting oCabra..."
$COMPOSE up -d $BUILD_SERVICES ollama gateway

ok "Containers started"

# ---------------------------------------------------------------------------
# 7. Wait for health check
# ---------------------------------------------------------------------------
info "Waiting for API to become healthy..."

MAX_WAIT=120
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
    if curl -sf http://localhost:8484/health >/dev/null 2>&1; then
        break
    fi
    sleep 3
    ELAPSED=$((ELAPSED + 3))
    printf "."
done
echo ""

if [ $ELAPSED -ge $MAX_WAIT ]; then
    warn "API did not become healthy within ${MAX_WAIT}s. Check logs with: docker compose logs api"
else
    ok "API is healthy"
fi

# ---------------------------------------------------------------------------
# 8. Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}=== oCabra is running ===${NC}"
echo ""
echo -e "  Dashboard:    ${GREEN}http://localhost:8484${NC}"
echo -e "  OpenAI API:   ${GREEN}http://localhost:8484/v1${NC}"
echo -e "  Ollama API:   ${GREEN}http://localhost:8484/api${NC}"
echo -e "  API docs:     ${GREEN}http://localhost:8484/docs${NC}"
echo ""
echo -e "  Admin user:   ${CYAN}$(grep '^OCABRA_ADMIN_USER=' .env 2>/dev/null | cut -d= -f2 || echo 'ocabra')${NC}"
echo -e "  Admin pass:   ${CYAN}(as configured in .env)${NC}"
echo ""
echo -e "  Useful commands:"
echo -e "    ${BOLD}docker compose logs -f api${NC}      Follow API logs"
echo -e "    ${BOLD}docker compose ps${NC}               Show running services"
echo -e "    ${BOLD}docker compose down${NC}             Stop all services"
echo ""
